name: fullstack-pytest
channels:
- conda-forge
- defaults
dependencies:
- aniso8601=3.0.0=py36_0
- attrs=17.4.0=py_0
- certifi=2018.1.18=py36_0
- click=6.7=py_1
- colorama=0.3.9=py36_0
- flask=0.12.2=py36_0
- flask-restalchemy=0.6.0=py36_0
- flask-restful=0.3.6=py36_0
- flask-sqlalchemy=2.3.2=py_0
- itsdangerous=0.24=py_2
- jinja2=2.10=py36_0
- markupsafe=1.0=py36_0
- more-itertools=4.1.0=py_0
- nodejs=8.10.0=0
- pip=9.0.1=py36_1
- pluggy=0.6.0=py_0
- py=1.5.3=py_0
- pycrypto=2.6.1=py36_1
- pytest=3.5.0=py36_0
- python=3.6.4=0
- python-dateutil=2.7.0=py_0
- pytz=2018.3=py_0
- setuptools=39.0.1=py36_0
- six=1.11.0=py36_1
- sqlalchemy=1.2.5=py36_0
- vs2015_runtime=14.0.25420=0
- werkzeug=0.14.1=py_0
- wheel=0.30.0=py36_2
- wincertstore=0.2=py36_0

